In [6]:
import numpy as np
from molecular_dynamics import run
from molecular_dynamics import calculate_configuration_force

In [3]:
sigma = 1
epsilon = 0.25
box_length = 3.5
m = 40
T = 1
dt = 0.005
initial_positions = np.loadtxt("../../data/init_crds_boxl_3.5-2.dat")
iterations_eq = 100
rng = np.random.default_rng(123)

In [4]:
configurations_eq, velocities_eq, potentials_eq, forces_eq, kinetic_energies_eq = run(initial_positions, T, m, dt, epsilon, sigma, box_length, iterations_eq)

Initial total energy 16826.105943736504
Final total energy 15727.779256861197
Configuration [[-1.2019639   0.04937449  1.3446687 ]
 [ 0.95762696  0.11536136 -1.3533073 ]
 [-0.18897434  0.52372794 -1.3651418 ]
 [-1.6199141  -0.04095865  0.19033262]
 [ 1.5412039  -0.75625664 -1.0000951 ]
 [-1.1155417  -1.6664609  -0.99065462]
 [-0.70326225 -0.13556516 -0.21229811]
 [ 1.0541455   1.3754934  -1.3764948 ]
 [-0.02434042  0.09024578  0.67682947]
 [ 0.57101383 -0.7828554  -1.0092848 ]
 [-0.75751888  1.3451685   0.35401673]
 [ 0.02166862  1.4060785  -0.56307622]
 [ 1.0072253  -0.18563138  0.94703502]
 [-0.17290178 -1.4916186   1.6233682 ]
 [ 0.86533713 -1.2297605   0.93751467]
 [ 1.7441529  -0.90349879  1.4845521 ]
 [ 0.22370473 -0.4626245   1.6397821 ]
 [-1.3001678   0.77344676 -1.1569506 ]
 [ 1.6386284   1.270492   -0.4038093 ]
 [ 0.4666099   0.85132912  1.231999  ]
 [-0.53585311 -1.3494132  -0.152944  ]
 [-0.87338446 -0.60012535 -1.2980486 ]
 [ 0.92194814  0.67006095  0.17410359]
 [-1.629674

In [8]:
potential0, forces0 = calculate_configuration_force(initial_positions, epsilon=0.25, sigma=1, box_length=3.5)

In [9]:
potential0

-29.472115017422276

In [10]:
forces0

array([[-2.97837648e+00,  1.99370573e+00,  9.34437278e-01],
       [ 1.16787806e+00,  4.28269404e+00, -2.86515324e-01],
       [-6.50629480e+00,  4.00610585e+00, -1.52552785e+01],
       [ 1.67744376e+00,  5.24678654e+00,  3.34207570e+00],
       [ 9.91388741e+00, -3.37625799e-01,  2.69018364e+00],
       [ 2.85866511e-01,  3.11126813e-01, -1.09593021e+00],
       [-8.33011169e+00, -1.92568216e+00,  3.70635379e+00],
       [-1.94374993e+00,  2.75572454e+00,  2.65897281e+00],
       [ 1.34103892e+00,  1.31567811e+00, -2.67528626e+00],
       [ 1.45540061e+01, -7.73549871e-01,  8.14323970e+00],
       [-2.53767405e+00, -3.99224691e+00, -1.57687152e+00],
       [ 1.09082966e+00, -3.79635335e+00, -2.74592442e+00],
       [-7.22135827e-01,  4.37513214e+00,  3.73105520e+00],
       [ 6.04226112e-01, -2.24349606e+00, -7.93834614e-03],
       [-6.00091127e-02,  2.06998663e+00, -3.99720897e-01],
       [ 1.23709154e-02,  3.91244461e-01,  1.16506071e+00],
       [ 7.48514594e+00, -9.16000839e-01