In [1]:
import numpy as np
from molecular_dynamics import calculate_configuration_force

In [2]:
sigma = 1
epsilon = 0.25
box_length = 3.5
m = 40
T = 1
dt = 0.005
initial_positions = np.loadtxt("../../data/init_crds_boxl_3.5-2.dat")
iterations = 10
rng = np.random.default_rng(123)

In [3]:
# initialize the velocity and shift according to total momentum
initial_velocities = rng.standard_normal((len(initial_positions), 3)) * np.sqrt(T)
px = np.sum(m * initial_velocities, axis=0)
initial_velocities -= px / len(initial_positions)

# initialize the potential and the forces
initial_potential, initial_forces = calculate_configuration_force(initial_positions, epsilon, sigma, box_length)

velocities = [initial_velocities]
potentials = [initial_potential]
configurations = [initial_positions]
forces = [initial_forces]

In [6]:
initial_positions

array([[-1.2019639 ,  0.04937449,  1.3446687 ],
       [ 0.95762696,  0.11536136, -1.3533073 ],
       [-0.18897434,  0.52372794, -1.3651418 ],
       [-1.6199141 , -0.04095865,  0.19033262],
       [ 1.5412039 , -0.75625664, -1.0000951 ],
       [-1.1155417 , -1.6664609 , -0.99065462],
       [-0.70326225, -0.13556516, -0.21229811],
       [ 1.0541455 ,  1.3754934 , -1.3764948 ],
       [-0.02434042,  0.09024578,  0.67682947],
       [ 0.57101383, -0.7828554 , -1.0092848 ],
       [-0.75751888,  1.3451685 ,  0.35401673],
       [ 0.02166862,  1.4060785 , -0.56307622],
       [ 1.0072253 , -0.18563138,  0.94703502],
       [-0.17290178, -1.4916186 ,  1.6233682 ],
       [ 0.86533713, -1.2297605 ,  0.93751467],
       [ 1.7441529 , -0.90349879,  1.4845521 ],
       [ 0.22370473, -0.4626245 ,  1.6397821 ],
       [-1.3001678 ,  0.77344676, -1.1569506 ],
       [ 1.6386284 ,  1.270492  , -0.4038093 ],
       [ 0.4666099 ,  0.85132912,  1.231999  ],
       [-0.53585311, -1.3494132 , -0.152

In [7]:
initial_velocities

array([[-2.07547955, -4.28955054, -1.94531597],
       [-0.89238378, -3.00153299, -2.65613744],
       [-1.72282185, -3.37981167, -3.54983669],
       [-1.40874732, -3.82459657, -4.75917164],
       [ 0.1058079 , -4.59285357, -2.23297182],
       [-0.95003708, -2.38973081, -3.89321065],
       [-1.39815306, -3.58399476, -5.44071233],
       [-0.25843676, -2.3801335 , -2.10643444],
       [-0.33158856, -4.06774178, -1.95133901],
       [-0.01232758, -3.52914305, -3.22812692],
       [-1.44812507, -5.15199609, -2.00701194],
       [-3.25840209, -4.29191124, -3.06886117],
       [-0.22647702, -2.16010265, -2.23991746],
       [-1.37787963, -3.19363633, -4.49484155],
       [ 0.34358032, -4.07823922, -3.90700039],
       [-1.7254183 , -3.98312522, -3.62602616],
       [ 1.20355174, -4.63994504, -3.20063349],
       [-1.05830831, -3.89349177, -3.17789537],
       [-1.56792106, -4.50517139, -4.09540174],
       [-2.57453282, -3.70545706, -2.24886489],
       [-1.62944234, -4.48037893, -3.549

In [8]:
initial_forces

array([[-2.97837648e+00,  1.99370573e+00,  9.34437278e-01],
       [ 1.16787806e+00,  4.28269404e+00, -2.86515324e-01],
       [-6.50629480e+00,  4.00610585e+00, -1.52552785e+01],
       [ 1.67744376e+00,  5.24678654e+00,  3.34207570e+00],
       [ 9.91388741e+00, -3.37625799e-01,  2.69018364e+00],
       [ 2.85866511e-01,  3.11126813e-01, -1.09593021e+00],
       [-8.33011169e+00, -1.92568216e+00,  3.70635379e+00],
       [-1.94374993e+00,  2.75572454e+00,  2.65897281e+00],
       [ 1.34103892e+00,  1.31567811e+00, -2.67528626e+00],
       [ 1.45540061e+01, -7.73549871e-01,  8.14323970e+00],
       [-2.53767405e+00, -3.99224691e+00, -1.57687152e+00],
       [ 1.09082966e+00, -3.79635335e+00, -2.74592442e+00],
       [-7.22135827e-01,  4.37513214e+00,  3.73105520e+00],
       [ 6.04226112e-01, -2.24349606e+00, -7.93834614e-03],
       [-6.00091127e-02,  2.06998663e+00, -3.99720897e-01],
       [ 1.23709154e-02,  3.91244461e-01,  1.16506071e+00],
       [ 7.48514594e+00, -9.16000839e-01

In [11]:
def verlet_position_update(position, velocity, force, mass, time_step):
    return position + time_step*velocity + ((time_step**2)/2*mass)*force

In [12]:
updated_positions = np.zeros((len(initial_positions), 3))
for particle_i in range(len(initial_positions)):
    new_position = verlet_position_update(initial_positions[particle_i, :], initial_velocities[particle_i, :], initial_forces[particle_i, :], m, 0.005)
    updated_positions[particle_i] = new_position


array([[-1.21383049,  0.02892359,  1.33540934],
       [ 0.95374898,  0.10249504, -1.36673124],
       [-0.2008416 ,  0.50883193, -1.39051862],
       [-1.62611911, -0.05745824,  0.1682078 ],
       [ 1.54668988, -0.77938972, -1.00991487],
       [-1.12014895, -1.67825399, -1.01066864],
       [-0.71441807, -0.15444797, -0.23764849],
       [ 1.05188144,  1.36497059, -1.38569749],
       [-0.02532785,  0.07056491,  0.66573513],
       [ 0.5782292 , -0.80088789, -1.02135381],
       [-0.76602834,  1.3174124 ,  0.34319323],
       [ 0.00592202,  1.38272077, -0.57979349],
       [ 1.00573185, -0.19424433,  0.93770096],
       [-0.17948907, -1.50870853,  1.60089002],
       [ 0.86702503, -1.2491167 ,  0.91777981],
       [ 1.73553199, -0.92321879,  1.4670045 ],
       [ 0.23346506, -0.48628223,  1.62945949],
       [-1.3049131 ,  0.75419816, -1.17364119],
       [ 1.63259487,  1.24728543, -0.42557203],
       [ 0.44707188,  0.83304778,  1.21857918],
       [-0.54398457, -1.37757539, -0.169