In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(1234)
initial_positions = np.loadtxt("../../data/init_crds_boxl_3.5-2.dat")
initial_positions

array([[-1.2019639 ,  0.04937449,  1.3446687 ],
       [ 0.95762696,  0.11536136, -1.3533073 ],
       [-0.18897434,  0.52372794, -1.3651418 ],
       [-1.6199141 , -0.04095865,  0.19033262],
       [ 1.5412039 , -0.75625664, -1.0000951 ],
       [-1.1155417 , -1.6664609 , -0.99065462],
       [-0.70326225, -0.13556516, -0.21229811],
       [ 1.0541455 ,  1.3754934 , -1.3764948 ],
       [-0.02434042,  0.09024578,  0.67682947],
       [ 0.57101383, -0.7828554 , -1.0092848 ],
       [-0.75751888,  1.3451685 ,  0.35401673],
       [ 0.02166862,  1.4060785 , -0.56307622],
       [ 1.0072253 , -0.18563138,  0.94703502],
       [-0.17290178, -1.4916186 ,  1.6233682 ],
       [ 0.86533713, -1.2297605 ,  0.93751467],
       [ 1.7441529 , -0.90349879,  1.4845521 ],
       [ 0.22370473, -0.4626245 ,  1.6397821 ],
       [-1.3001678 ,  0.77344676, -1.1569506 ],
       [ 1.6386284 ,  1.270492  , -0.4038093 ],
       [ 0.4666099 ,  0.85132912,  1.231999  ],
       [-0.53585311, -1.3494132 , -0.152

In [3]:
from molecular_dynamics import calculate_configuration_force

potential0, force0 = calculate_configuration_force(initial_positions, epsilon=0.25, sigma=1, box_length=3.5)
print("Initial potential", potential0)
print("Initial forces", force0)

Initial potential -29.472115017422283
Initial forces [[ -2.97837648   1.99370573   0.93443728]
 [  1.55677987   4.26354883  -0.51921188]
 [ -6.09136609   3.29395914 -15.77792601]
 [  2.02149539   5.36256787   4.26937576]
 [ 10.51332135  -0.14044396   3.18859249]
 [ -0.38865308   1.01391586  -1.18461974]
 [  1.38356628  -2.865527    -1.24086902]
 [ -1.60915407   1.89549032   3.00377436]
 [  0.03674392   1.34986474  -1.96470148]
 [ -8.46651855  -6.29029246   9.87245059]
 [ -2.61564248  -5.17943027  -2.19099747]
 [  0.2417948   -4.27326044  -3.81911595]
 [  1.2509662    4.75133719   5.36481179]
 [  0.91010346  -2.57999174   1.89503713]
 [ -1.57809634  -1.61422931   1.03976648]
 [  1.27708464   0.25402929  -1.96253564]
 [ -2.20455394   4.10479666  -6.4870063 ]
 [  0.64906226  -2.32067543  -2.20748753]
 [  1.7882653   -0.61876732   0.1181668 ]
 [-11.6269295    1.81223512  -0.47499272]
 [  0.80859363  12.25412835  -2.02435801]
 [  0.99555371   0.2380974   -0.12230868]
 [ -0.21081491  -0.8832

In [2]:
from molecular_dynamics import run
import numpy as np
initial_positions = np.loadtxt("../../data/init_crds_boxl_3.5-2.dat")

potentials, kinetics, energies, forces, velocities, positions = run(
    positions=initial_positions, 
    T=1.0,
    m=1.,
    dt=0.005,
    sigma = 1,
    epsilon = 0.25,
    box_length = 3.5,
    iterations=100
)

-29.472115017422283
-32.8085825092346
-33.68340803600208
-34.21188380759079
-34.58024525507257
-34.85381363572533
-35.064651273868705
-35.23090442000673
-35.36445606907386
-35.47413168869576
-35.56512728768915
-35.640389035893044
-35.70320563156729
-35.757398006417525
-35.80472315904752
-35.84501205355672
-35.87922609620668
-35.90831716336172
-35.93304270606256
-35.9540257348786
-35.97219481876485
-35.98720071736077
-36.00038339060955
-36.01187465388697
-36.02164525064244
-36.02978710803018
-36.036705965477296
-36.04317254128792
-36.049756357522874
-36.05535406704857
-36.06020714663131
-36.06497615144104
-36.0690408355938
-36.07244214116578
-36.07527692747516
-36.07749397201251
-36.079174729424714
-36.08036499089788
-36.0810730487066
-36.08130291906967
-36.081069374319966
-36.0805929721301
-36.07968760191198
-36.07829392782823
-36.07641650640907
-36.07406084901733
-36.07135742027733
-36.06821955743218
-36.064600862593544
-36.060558303521276
-36.056118216115024
-36.05118687732146
-36.04