In [1]:
import numpy as np

from langevian_protein import run

In [2]:
protein_chain = ['H', 'P', 'P', 'H', 'H']
coordinates = np.array([
    [0,0,1],
    [0,0,2],
    [0,0,3],
    [0,0,4],
    [0,0,5]
])
friction = 0.05
m = 1
kT = 2
dt = 0.003
k = 20
l = 1
iterations = 10

In [3]:
potential_record, kinetic_record, energies, temperatures, forces, velocities, positions = run(
    coordinates, 
    m, 
    protein_chain, 
    k,
    l, 
    friction, 
    kT, 
    dt, 
    iterations
)

1.0
2.0
3.0
4.0
1.0
2.0
3.0
1.0
2.0
1.0
[[0 0 1]
 [0 0 2]
 [0 0 3]
 [0 0 4]
 [0 0 5]]
1.0
1.0
3.0
3.0
0.0
2.0
2.0
2.0
2.0
0.0
[[0 0 1]
 [0 0 2]
 [0 0 2]
 [0 0 4]
 [0 0 4]]
3719550786.1820083
3719550786.1820083
3719550786.1820083
3719550786.1820083
0.0
0.0
0.0
0.0
0.0
0.0
[[          0           0           1]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648]]
3718881317.3679686
3718881317.3679686
3718881317.3679686
3718881317.3679686
0.0
0.0
0.0
0.0
0.0
0.0
[[     386518      386518      386519]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648]]
3717542601.442392
3717542601.442392
3717542601.442392
3717542601.442392
0.0
0.0
0.0
0.0
0.0
0.0
[[    1159426     1159426     1159427]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -2147483648 -2147483648]
 [-2147483648 -21474836

C:\Users\Joshua\Documents\Modeling The Living Cell 23\scripts\PS5\langevian_protein.py:10: RuntimeWarning: invalid value encountered in scalar divide
  return (-k * r * (abs(r) - l))/abs(r)
C:\Users\Joshua\Documents\Modeling The Living Cell 23\scripts\PS4\molecular_dynamics.py:80: RuntimeWarning: invalid value encountered in cast
  positions[:] = verlet_position_update(positions, velocities, forces, m, dt)
C:\Users\Joshua\Documents\Modeling The Living Cell 23\scripts\PS4\molecular_dynamics.py:10: RuntimeWarning: divide by zero encountered in scalar divide
  return 4 * epsilon * ((sigma ** 12 / distance ** 12) - (sigma ** 6 / distance ** 6))
C:\Users\Joshua\Documents\Modeling The Living Cell 23\scripts\PS4\molecular_dynamics.py:10: RuntimeWarning: invalid value encountered in scalar subtract
  return 4 * epsilon * ((sigma ** 12 / distance ** 12) - (sigma ** 6 / distance ** 6))
C:\Users\Joshua\Documents\Modeling The Living Cell 23\scripts\PS4\molecular_dynamics.py:21: RuntimeWarning: div